repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.1'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
        args: ["--no-update"]
    -   id: poetry-export
    -   id: poetry-install

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: "check type hints"
        additional_dependencies: [pydantic==2.5.2, redis==5.0.1]

-   repo: https://github.com/pycqa/flake8
    rev: '7.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-builtins, flake8-quotes]
