# all-in-one docker compose

services:
  redis:
    build:
      dockerfile: ./services/redis/Dockerfile
    volumes:
      - redis_data:/data

  app:
    build:
      dockerfile: ./src/Dockerfile
      target: base-app
    volumes:
      - ${ENV_FILE}:/app/.env
    depends_on:
      redis:
        condition: "service_started"
    healthcheck:
      test: [ "CMD-SHELL", "curl app:8000/ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app-celery:
    build:
      dockerfile: ./src/Dockerfile
      target: celery-app
    volumes:
      - ${ENV_FILE}:/app/.env
    depends_on:
      redis:
        condition: "service_started"

  nginx:
    build:
      dockerfile: ./services/nginx/Dockerfile
    depends_on:
      app:
          condition: "service_healthy"
    ports:
      - 8000:8000


volumes:
  redis_data:
