# Compose file for local development. Start Redis container only

services:
  redis:
    build:
      dockerfile: ./services/redis/Dockerfile
    volumes:
      - redis_data:/data
    network_mode: host

  # app:
  #  build:
  #    dockerfile: ./src/Dockerfile
  #  depends_on:
  #    redis:
  #      condition: "service_started"
  #    db:
  #      condition: "service_healthy"
  #  network_mode: host
  #  ports:
  #    - 8000:8000

volumes:
  redis_data:
